SHOW PARAMETERS LIKE 'CORTEX_ENABLED_CROSS_REGION' IN ACCOUNT;
ALTER ACCOUNT SET CORTEX_ENABLED_CROSS_REGION = 'ANY_REGION';

CREATE WAREHOUSE IF NOT EXISTS CORTEX_WH
  WITH WAREHOUSE_SIZE = 'XLARGE'
  AUTO_SUSPEND = 5
  AUTO_RESUME = TRUE;

USE WAREHOUSE CORTEX_WH;
